"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
add_newline = false

# NOTE: hand-picked from color palette
# https://github.com/enkia/tokyo-night-vscode-theme?tab=readme-ov-file#tokyo-night-and-tokyo-night-storm
format = """
$os\
[î‚°](fg:prev_bg bg:#414868)\
$directory\
[î‚°](fg:prev_bg bg:#343b58)\
$git_branch\
$git_status\
[î‚°](fg:prev_bg bg:#24283b)\
$git_metrics\
[î‚°](fg:prev_bg bg:#1a1b26)\
$nix_shell\
[î‚°](fg:prev_bg)\
"""

right_format = """
[î‚²](fg:#24283b)\
$cmd_duration\
[î‚²](fg:#343b58 bg:#24283b)\
$time
"""

[os]
style = 'fg:#cfc9c2 bg:#565f89'
format = '[ $symbol]($style)'
disabled = false

[directory]
style = 'fg:#b4f9f8 bg:prev_bg'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = 'â€¦/'

[git_branch]
symbol = 'ï˜'
style = 'fg:#e0af68 bg:prev_bg'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'fg:#e0af68 bg:prev_bg'
format = '[$state($all_status$ahead_behind )]($style)'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[git_metrics]
added_style = 'fg:#9ece6a bg:prev_bg'
deleted_style = 'fg:#f7768e bg:prev_bg'
format = '([ +$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[nix_shell]
style = 'fg:#b4f9f8 bg:prev_bg'

[python]
style = 'fg:#9ece6a bg:prev_bg'
format = '[${symbol}${version}\(${virtualenv}\)]($style)'
symbol = 'ğŸ'
version_format = '${major}.${minor}'

[cmd_duration]
disabled = false
min_time = 500
style = 'fg:#b4f9f8 bg:#24283b'
format = '[ $duration ]($style)'

[time]
disabled = false
time_format = '%R'
style = 'fg:#a9b1d6 bg:#343b58'
format = '[ ïº $time ]($style)'

[os.symbols]
Alpine = 'ïŒ€ '
Amazon = 'ï‰° '
Android = 'ï…» '
Arch = 'ïŒƒ '
CentOS = 'ïŒ„ '
Debian = 'ïŒ† '
DragonFly = 'îŠ '
Emscripten = 'ïˆ… '
EndeavourOS = 'ï†— '
Fedora = 'ïŒŠ '
FreeBSD = 'ïŒŒ '
Garuda = ' '
Gentoo = 'ïŒ '
HardenedBSD = 'ï²Š '
Illumos = 'ïœ· '
Linux = 'ïŒš '
Macos = 'ïŒ‚ '
Manjaro = 'ïŒ’ '
Mariner = 'ï‡ '
MidnightBSD = 'ï†† '
Mint = 'ïŒ '
NetBSD = 'ï€¤ '
NixOS = 'ïŒ“ '
OpenBSD = 'ïœ¹ '
openSUSE = 'ïŒ” '
OracleLinux = 'ï ¶ '
Pop = 'îŠ£ '
Raspbian = 'ïŒ• '
Redhat = 'ïŒ– '
RedHatEnterprise = 'ïŒ– '
Redox = 'ï”— '
Solus = 'ï´± '
SUSE = 'ïŒ” '
Ubuntu = 'ïŒ› '
Unknown = 'ïˆ­ '
Windows = 'ï¡± '

